export const tasks = [
  {
    id: 1,
    type: 'Tracking',
    frequency: 'Daily',
    description: 'Exercise',
    category:'Health',
    dates: [
      {
        date: '2024-10-01',
        state: 'closed',
      },
      {
        date: '2024-10-02',
        state: 'open',
      },
      {
        date: '2024-10-09',
        state: 'open',
      },
      {
        date: '2024-10-12',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "1",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 2,
    type: 'Deadline',
    frequency: 'One-time',
    description: 'Pay a medical bill',
    category:'Tasks',
    dates: [
      {
        date: '2023-10-08',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 3,
    type: 'Floating',
    frequency: 'One-time',
    description: 'Watch Antman movie',
    category:'Movies',
    dates: [
      {
        date: '2023-10-12',
        state: 'open',
      },
    ], 
    priority: '1',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 4,
    type: 'Floating',
    frequency: 'Ongoing',
    description: 'Watch show, season 1',
    category:'Shows',
    dates: [
      {
        date: '2023-10-12',
        state: 'closed',
      },
    ], 
    priority: '1',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 5,
    type: 'Floating',
    frequency: 'One-time',
    description: 'Watch the Matrix',
    category:'Movies',
    dates: [
      {
        date: '2001-10-08',
        state: 'closed',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 6,
    type: 'Deadline',
    frequency: 'Recurring',
    description: 'Pay Bills',
    category:'Finance',
    dates: [
      {
        date: '2024-09-08',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 7,
    type: 'Deadline',
    frequency: 'Recurring',
    description: 'Pay Insurance',
    category:'Finance',
    dates: [
      {
        date: '2024-09-08',
        state: 'closed',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 8,
    type: 'Periodic',
    frequency: 'One-time',
    description: 'Clean House',
    category:'Cleaning',
    dates: [
      {
        date: '2023-10-08',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 9,
    type: 'Tracking',
    frequency: 'Recurring',
    description: 'Mow the Lawn',
    category:'Chore',
    dates: [
      {
        date: '2024-10-08',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "7",
    recurStart: '',
    recurEnd: '',
  },
  {
    id: 10,
    type: 'Event',
    frequency: 'One-time',
    description: 'Birthday',
    category:'Event',
    dates: [
      {
        date: '2024-10-09',
        state: 'open',
      },
    ], 
    priority: '1',
    notes: '',
    recurDays: "0",
    recurStart: '',
    recurEnd: '',
  },
]