export const tasks = [
  {
  id: 1,
  description: 'Test 1',
  category: 'House',
  status: 'Started',
  tags: [],
  dueDate: '8/1/2020',
  completedDate: '',
  actual: 10,
  goal: 200,
  completed: false,
  priority: '1',
  dueWeek: 1,
  dueMonth: 1,
  assigned: 'Adam',
  contact: 'Dan',
  notes:'this is a test note',
  isActive: true,
},
{
  id: 2,
  description: 'Test 2',
  category: 'Finances',
  status: 'Not Started',
  tags: [],
  startDate: '',
  duedate: '8/1/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: true,
  priority: '1',
  dueWeek: 1,
  dueMonth: 1,
  assigned: 'John',
  contact: 'Jeff',
  isActive: true,
},
{
  id: 3,
  description: 'Test 3',
  category: 'Fitness',
  status: 'Not Started',
  tags: [],
  duedate: '8/16/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: false,
  priority: 1,
  dueWeek: 2,
  dueMonth: 2,
  assigned: 'Adam',
  contact: 'Dan',
  isActive: true,
},
{
  id: 4,
  description: 'Test 4',
  category: 'Finances',
  status: 'In Progress',
  tags: [],
  dueDate: '8/17/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: false,
  priority: 1,
  dueWeek: 3,
  dueMonth: 3,
  assigned: 'Adam',
  contact: 'Dan',
  isActive: true,
},
{
  id: 5,
  description: 'Test 5',
  category: 'House',
  status: 'Complete',
  tags: [],
  dueDate: '8/19/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: false,
  priority: 1,
  dueWeek: 3,
  dueMonth: 4,
  assigned: 'Adam',
  contact: 'Dan',
  isActive: true,
},
{
  id: 6,
  description: 'Test 6',
  category: 'House',
  status: 'In Progress',
  tags: [],
  dueDate: '8/19/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: false,
  priority: 1,
  dueWeek: 4,
  dueMonth: 5,
  assigned: 'Adam',
  contact: 'Dan',
  isActive: true,
},
{
  id: 7,
  description: 'Test 7',
  category: 'Fitness',
  status: 'Complete',
  tags: [],
  dueDate: '8/20/2020',
  completedDate: '',
  actual: 0,
  goal: 0,
  completed: false,
  priority: 1,
  dueWeek: 3,
  dueMonth: 2,
  assigned: 'Adam',
  isActive: true,
  contact: 'Dan',
},
{
  id: 1,
  description: 'First Task',
  category:'',
  status: '',
  dueDate: '8/17/2020',
  actual: 0,
  goal: 0,
  priority: '',
  assigned: '',
  contact: '',
  isActive: false,
  workTime: [],
  tags: [],
  completedDate:  '',
  dueWeek: '8/17/2020',
  dueMonth: 'August 2020',
  notes: '',
}
]